name: clearbias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Changed from >=3.12 to 3.11 for better compatibility
  - matplotlib
  - pandas
  - pytest
  - scikit-learn
  - seaborn
  - statsmodels
  - notebook
  - jupyterlab
  - ipython
  - plotly
  - scikit-image
  - optuna
  - sqlalchemy
  - numpy>=1.21,<1.24  # Specify compatible numpy version
  - networkx>=2.8,<3.0  # Add networkx constraint for pgmpy compatibility
  - rpy2
  - six
  - prettytable
  - pydot
  - imbalanced-learn
  - pip
  - pip:
    - aif360
    - ucimlrepo
    - boto
    - doubleml
    - hdbscan
    - lime
    - mapie
    - parsimonious
    - patsy
    - ucimlrepo
    - z3-solver
    - sdv
    - ipython-extensions
    - scikit-learn-intelex
    - sliceline
    - divexplorer
    - gurobipy
    - ete3
    - pyrulelearn
    - pysat
    - pgmpy
    - feature-engine
    - python-sat
    - gpkit
    - Cython
    - xarray<2023.1.0  # Add xarray with version constraint for pysat compatibility
    - Orange