[project]
name = "clearbias"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aif360>=0.6.1",
    "boto>=2.49.0",
    "doubleml>=0.9.3",
    "hdbscan>=0.8.40",
    "lime>=0.2.0.1",
    "mapie>=0.9.2",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "parsimonious>=0.10.0",
    "patsy>=1.0.1",
    "pygad>=3.4.0",
    "pytest>=8.3.4",
    "scikit-learn-intelex>=2025.2.0",
    "scikit-learn>=1.5.2",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.38",
    "statsmodels>=0.14.4",
    "torch>=2.6.0",
    "ucimlrepo>=0.0.7",
    "z3-solver>=4.14.0.0",
    "sdv>=1.18.0",
    "notebook>=7.3.2",
    "jupyterlab>=4.3.5",
]
